### PR TITLE
Update tests to the latest CodeFlare operator version

### PR DESCRIPTION
**Pull request by sutaakar**
Update test go.mod and go.sum to the latest CodeFlare operator version

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by sutaakar** [comment]
Future task is to move route creation into support package to avoid duplication.
Right now I have copy pasted the code to make OpenShift CI working soon.

**Review by winklerm — APPROVED** [review]
Thanks!

**Pull request merged**
