### PR TITLE
Add support for Kueue in KFTO e2e test

### PR DESCRIPTION
**Pull request by sutaakar**
Added support for Kueue CR creation directly into KFTO e2e test.

## Description

Existing test implementation relied on externally created Kueue CRs. The need to externally provided Kueue CRs is now removed as test manages its own Kueue resources.
Also added some additional assertions, provided resource requests and limits for job and Kueue label.

TODO: 
- Move PytorchJob helper functions to codeflare-common repository.
- Fix PR check to properly run test.

## How Has This Been Tested?

Tested by manually running test against OCP cluster with nightly ODH deployed.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [ ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tedhtchang — COMMENTED** [review]
Tested with the following command:
```bash
# Install KinD
# Install KFTO
go test ./tests/kfto
```

Test pytorchjob ran successfully and terminated but the test Failed
```
W0430 15:12:05.124724  301123 warnings.go:70] unknown field "spec.pytorchReplicaSpecs.Master.template.metadata.creationTimestamp"
--- FAIL: TestPytorchjobWithSFTtrainer (300.13s)
    kfto_kueue_sft_test.go:70: Created ConfigMap test-ns-x5p8h/config-jwscj successfully
    kfto_kueue_sft_test.go:73: Created Kueue ResourceFlavor rf-9szst successfully
    kfto_kueue_sft_test.go:98: Created Kueue ClusterQueue cq-d52vd successfully
    kfto_kueue_sft_test.go:100: Created Kueue LocalQueue test-ns-x5p8h/lq-cpvnf successfully
    kfto_kueue_sft_test.go:179: Created PytorchJob test-ns-x5p8h/kfto-sft successfully
    kfto_kueue_sft_test.go:183:
        Timed out after 300.001s.
        Expected
            <[]*v1beta1.Workload | len:0, cap:0>: []
        to have length 1
    test.go:144: Retrieving Pod Container test-ns-x5p8h/kfto-sft-master-0/pytorch logs
    test.go:132: Creating ephemeral output directory as CODEFLARE_TEST_OUTPUT_DIR env variable is unset
    test.go:135: Output directory has been created at: /tmp/TestPytorchjobWithSFTtrainer2923813851/001
FAIL
FAIL	github.com/opendatahub-io/distributed-workloads/tests/kfto	300.432s
FAIL
```

**Comment by sutaakar** [comment]
@tedhtchang If you installed Kueue from Makefile then it wont work properly as makefile use rhoai manifest which is AFAIK tailored for OpenShift. I am not exactly sure what are the differences, but if you install upstream Kueue then it should work well on KinD. rhoai manifest works well on OpenShift.

Thinking whether it would have sense to provide alternative installation option in Makefile to install from upstream Kueue, what do you think?

**Review by tedhtchang — APPROVED** [review]
It works with OCP
```
make setup-kueue
make setup-kfto
go test ./tests/kfto
# ok  	github.com/opendatahub-io/distributed-workloads/tests/kfto	125.890s
```
Tested on both  `KinD + upstream kueue + upstram kfto` or `ODH managed kueue +kfto` but cannot enqueue for some reason.

**Comment by sutaakar** [comment]
weird, I have tried upstream setup:
- KinD provisioned from https://github.com/project-codeflare/codeflare-operator using `make kind-e2e`
- Kueue installed using `kubectl apply --server-side -f https://github.com/kubernetes-sigs/kueue/releases/download/v0.6.2/manifests.yaml`
- Training operator provisioned using `kubectl apply -k "github.com/kubeflow/training-operator/manifests/overlays/standalone?ref=v1.7.0"`

Test successfully created a Pod (had to terminate test in this phase as I run on limited connection and SFT image is large).

**Pull request merged**
