### PR TITLE
update spawner page instructions

### PR DESCRIPTION
**Pull request by MichaelClifford**

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@tedhtchang Let me know if you think this update on accessing the spawner page is sufficient or if it needs more detail. :smile:

**Review by tedhtchang — COMMENTED** [review]
@MichaelClifford  This helps. For me it was `https://odh-dashboard-odh.apps.<your cluster's uri>` because I installed the Kfdef in odh namespace.

**Comment by MichaelClifford** [comment]
@tedhtchang Made the update you requested.

**Comment by tedhtchang** [comment]
@MichaelClifford Thanks. LGTM.

**Review by tedhtchang — APPROVED** [review]

**Review by tedhtchang — APPROVED** [review]

**Review by accorvin — APPROVED** [review]

**Pull request merged**
