### PR TITLE
Move TestMnistRay from integration tests repo to ODH DW repo

### PR DESCRIPTION
**Pull request by sutaakar**
## Description

As part of test reconciliation I am moving TestMnistRay from https://github.com/project-codeflare/integration-tests here. That way all the integration tests for DW stack are in one place.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by jiripetrlik — APPROVED** [review]

**Review by astefanutti — COMMENTED** [review]
I would have suggested to add it to the `tests/ray` directory instead of `tests/odh` :)

**Comment by abhijeet-dhumal** [comment]
> I would have suggested to add it to the `tests/ray` directory instead of `tests/odh` :)

@astefanutti Please correct me if I'm wrong, here I suppose currently this integration test is common for all Distributed workload components, so `test/odh` seems better option instead of `test/ray `:roll_eyes:

**Comment by sutaakar** [comment]
I kept `odh` folder name there as the test is using Notebook for running SDK.
There will be (probably) more similar tests in future using Notebook from ODH/RHOAI and IMHO it would be good to keep them on single place.

**Comment by astefanutti** [comment]
I see, the criteria to name that folder is the "target" environment.

My suggestion was to organise the tests by the main "component under test", like I assume it was the case for `tests/kfto`.

Following that logic, even if we use a notebook in the context of ODH, the main component under test is Ray, so you could have inside `tests/ray` some tests that use notebook / odh, and some other that directly use the SDK, like for local interactive use case, or using the RayCluster API directly.

Also, at some point, there will probably be some tests for the KFTO that use notebook as well.

**Pull request merged**
