### PR TITLE
add KubeRay manifests

### PR DESCRIPTION
**Pull request by MichaelClifford**
* Added All the KubeRay Manifests from [ODH Contrib Manifests](https://github.com/opendatahub-io-contrib/odh-contrib-manifests/tree/main/ray) into this repo. 
* Updated the KfDef to pull the KubeRay manifests from this repo.
* Updated the README and QuickStart to account for new content in this repo.

### CODE REVIEW

**Comment by tedhtchang** [comment]
@MichaelClifford Could you also change the following paragraph in quick-start because it's outdated by the `oc apply -f odh-core.yaml -n opendatahub`.
```
If you do not currently have Open Data Hub installed on your cluster, you can find instructions for installing it [here](https://opendatahub.io/docs/getting-started/quick-installation.html). 
To
If you do not currently have Open Data Hub installed on your cluster, you can find instructions for Installing the Open Data Hub Operator [here](https://opendatahub.io/docs/getting-started/quick-installation.html). 
```

**Comment by accorvin** [comment]
@MichaelClifford can you rebase this?

**Comment by MichaelClifford** [comment]
Thanks for the reviews @accorvin and @tedhtchang,rebased and changes made.

**Review by accorvin — APPROVED** [review]
Confirmed working as expected.

**Review by tedhtchang — APPROVED** [review]
/lgtm
tested
```
oc apply -k codeflare-stack/base/
oc create -k ray/operator/base -n opendatahub
# Then ran batch job notebook from my laptop w/ (the main branch codeflare-sdk installed)
```

**Review by anishasthana — APPROVED** [review]

**Pull request merged**
