### PR TITLE
Use newer SDK parameters to set Ray head memory requests and limits

### PR DESCRIPTION
**Pull request by astefanutti**
## Description

Fixes for https://issues.redhat.com/browse/RHOAIENG-14195.

## How Has This Been Tested?

Run the LLM fine-tuning with Ray example.

## Merge criteria:

- [x] The commits are squashed in a cohesive manner and have meaningful messages.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Comment by abhijeet-dhumal** [comment]
Could these changes be made in ODH test ray-finetune-llm-deepspeed_test.go too here ? : https://github.com/opendatahub-io/distributed-workloads/blob/e1aa8cc2403c04a424044d18758a0f6a5210ac73/tests/odh/ray_finetune_llm_deepspeed_test.go#L62

**Review by abhijeet-dhumal — COMMENTED** [review]
/lgtm

**Comment by astefanutti** [comment]
@abhijeet-dhumal thanks a lot for the review, I've updated these parameters in the e2e test as well. PTAL.

**Review by sutaakar — COMMENTED** [review]
/lgtm

**Pull request merged**
